language: java

jdk:
  - openjdk12

# whitelist branches
branches:
  only:
    - master
    - dev
      
# overrides travis 'install' step
# this installs dependencies. Using default profile
install:
  - java -version
  - mvn --version
  - mvn --batch-mode clean install -DskipTests=true

# overrides travis 'script' step
script:
  - mvn --batch-mode clean package -Pjrockit
  - mvn --batch-mode clean package -Pjava8
  - mvn --batch-mode clean package -Pmpje
  - mvn --batch-mode clean package -Pjava12

notifications:
  email: false