language: java

sudo: false

jdk:
  - oraclejdk8

# whitelist branches
branches:
  only:
    - master
    - dev
      
# overrides travis 'install' step
# this installs dependencies. Using default profile
install: mvn clean install -DskipTests=true

# overrides travis 'script' step
script: mvn clean package -Pjava7 && mvn clean package -Pjava8 && mvn clean package -Pjrockit && mvn clean package -Pmpje

notifications:
  email:
    - fabri1983@gmail.com