language: java

sudo: false

jdk:
  - oraclejdk8
  
# overrides travis 'install' step
# this installs dependencies. Using default profile
install: mvn clean install -DskipTests=true

# whitelist branches
branches:
  only:
    - master
    - dev

# overrides travis 'script' step
script: mvn clean package -Pjava7 && mvn clean package -Pjava8 && mvn clean package -Pjrockit && mvn clean package -Pmpje

# I will need to set something up to catch these.
notifications:
  email:
    - fabri1983@gmail.com