sudo: false
language: java

jdk:
  - openjdk11

branches:
  only:
    - master
    - dev

cache:
  directories:
    - $HOME/.m2

# Overrides travis 'install' step.
# This installs dependencies using default profile.
install:
  - java -version
  - mvn --version
  - mvn --batch-mode clean compile -P java8,proguard -DskipTests=true

# overrides travis 'script' step
script:
  - mvn --batch-mode clean package -P java8,proguard -DskipTests=true
  - mvn --batch-mode clean package -P mpje8,proguard -DskipTests=true
  - mvn --batch-mode clean package -P java11,proguard -DskipTests=true
  - mvn --batch-mode clean package -P mpje11,proguard

notifications:
  email:
    on_success: never
    on_failure: always