sudo: false
language: java

jdk:
  - openjdk11

branches:
  only:
    - master
    - dev

cache:
  directories:
    - $HOME/.m2

# Overrides travis 'install' step.
# This installs dependencies using default profile.
install:
  - java -version
  - mvn --version
  - mvn --batch-mode clean compile -Pjava8 -DskipTests=true

# overrides travis 'script' step
script:
  - mvn --batch-mode clean package -Pjava8
  - mvn --batch-mode clean package -Pmpje
  - mvn --batch-mode clean package -Pjava11

notifications:
  email:
    on_success: never
    on_failure: always