
######################################################################################################
FROM oracle/graalvm-ce:20.0.0-java11
ARG E2_JAR

ENV ENV_E2_JAR=${E2_JAR}

RUN gu install native-image \
 && mkdir -p /app

COPY ${E2_JAR} /app/

WORKDIR /app

# Entry with exec so jvm flags are correctly gathered
ENTRYPOINT exec native-image --verbose -jar ${ENV_E2_JAR}
